#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh
#       is noncompliant, but you have some other compliant shell such as ksh or
#       bash, then you need to set the SHELL environment variable to point to
#       that shell before running this script, e.g.:
#           SHELL=/usr/bin/ksh gradle
#
#       Also, if you are using Gradle from an SDK-style Gradle Wrapper, you can
#       set the GRADLE_OPTS environment variable and then run this script.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$(ls -ld "$app_path")
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
APP_HOME=$(cd "${APP_HOME:-./}" && pwd -P) || exit

# Use the maximum available file descriptors if possible, but let the user override.
MAX_FD=maximum
warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$(uname)" in
  CYGWIN* )
    cygwin=true
    ;;
  Darwin* )
    darwin=true
    ;;
  MSYS* | MINGW* )
    msys=true
    ;;
  NONSTOP* )
    nonstop=true
    ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in
      max*)
        # In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC3045
        MAX_FD=$( ulimit -H -n )
        if [ $? -eq 0 ] ; then
            # shellcheck disable=SC3045
            ulimit -n $MAX_FD
        else
            warn "Could not query maximum file descriptor limit"
        fi
        ;;
      esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if dedicated module-path is available)
#   * --module-path
#   * --module (only if dedicated module is available)
#   * --module (only if dedicated module is available)

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$(cygpath --path --mixed "$APP_HOME")
    CLASSPATH=$(cygpath --path --mixed "$CLASSPATH")

    JAVACMD=$(cygpath --unix "$JAVACMD")

    # Now convert the arguments - we need to handle escape sequences for spaces and quotes.
    # We will use printf to do this because shell's quoting is impossible to get right.
    # We only need to handle spaces, not arbitrary characters because they are already quoted.
    # Spaces are denoted by `%SPACE%` and quotes are denoted by `%DOUBLE_QUOTE%`.
    orig_args=$(printf "%s" "$QUOTED_ARGS")
    for a in $orig_args; do
        case $a in
          *%SPACE%*)
            args="${args} \"${a//%SPACE%/ }\""
            ;;
          *%DOUBLE_QUOTE%*)
            args="${args} \"${a//%DOUBLE_QUOTE%/\"}\""
            ;;
          *)
            args="${args} $a"
            ;;
        esac
    done
    # Support old IFS-based fallback
    # It's better to rely on QUOTED_ARGS variable to be set by the user (as it was with older Gradle)
    if [ -z "$QUOTED_ARGS" ]; then
        QUOTED_ARGS=$args
    fi
fi

# Collect all arguments for the java command;
#   * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $GRADLE_OPTS can contain fragments of
#     shell script including quotes and variable substitutions, so put them in
#     double quotes to make sure that they get re-expanded; and
#   * put everything else in single quotes, so that it is not re-expanded.

set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$QUOTED_ARGS" "$@"

# Stop when "xargs" is not available.
if ! command -v xargs >/dev/null 2>&1
then
    die "xargs is not available"
fi

# Use "xargs" to parse quoted args.
# Without this, values containing spaces and quotes would be broken.
# The backslashes are only needed for Cygwin / MSYS (see above).
eval "set -- $(
    printf '%s\n' "$QUOTED_ARGS" |
    xargs -0 printf '%s\n' |
    sed "s/'/'\\\\''/g;" |
    xargs printf " '%s'"
)"

# Add the arguments in batches.
# shellcheck disable=SC2086
{
    if [ -n "$JAVA_OPTS" ]; then
        DEFAULT_JVM_OPTS='"$JAVA_OPTS"'
    fi
    if [ -n "$GRADLE_OPTS" ]; then
        DEFAULT_JVM_OPTS='"$GRADLE_OPTS"'
    fi
    DEFAULT_JVM_OPTS='"$-Dorg.gradle.appname=$APP_BASE_NAME"'
} 2>/dev/null

# Evaluate the DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS variables, then
# add them to the command line.
# shellcheck disable=SC2086
{
    if [ -n "$JAVA_OPTS" ]; then
        DEFAULT_JVM_OPTS="$DEFAULT_JVM_OPTS $JAVA_OPTS"
    fi
    if [ -n "$GRADLE_OPTS" ]; then
        DEFAULT_JVM_OPTS="$DEFAULT_JVM_OPTS $GRADLE_OPTS"
    fi
    # Add DEFAULT_JVM_OPTS to command line.
    eval "set -- $DEFAULT_JVM_OPTS $@"
}

# Escape application args before saving them to a file
# Save the arguments into a file to support working directory being not
# the same as the application location. We need to quote $@ so it gets saved
# properly with spaces and quotes. But we cannot use printf because some
# shells mess with quotes. To avoid all that, we use the following ugly
# approach.
{
    # If we have printf (which is almost always the case), we can use it to
    # quote the arguments.
    if command -v printf >/dev/null 2>&1; then
        # Format the arguments into a string, replacing special characters.
        # The sed command replaces spaces with %SPACE% and quotes with
        # %DOUBLE_QUOTE% so we can use printf to quote them.
        # The eval is needed to expand the %ENV% variables.
        ARGS=$(printf '%s\n' "$@" | sed -e 's/ /%SPACE%/g' -e 's/"/%DOUBLE_QUOTE%/g')
        # Now we can use printf to quote the arguments.
        QUOTED_ARGS=$(printf '%s\n' "$ARGS" | xargs -0 printf ' "%s"')
        # Strip the leading space.
        QUOTED_ARGS="${QUOTED_ARGS# }"
        # Now replace the %SPACE% and %DOUBLE_QUOTE% back.
        QUOTED_ARGS=$(printf '%s\n' "$QUOTED_ARGS" | sed -e 's/%SPACE%/ /g' -e 's/%DOUBLE_QUOTE%/" "/g')
    else
        # Otherwise, fallback to the original approach.
        QUOTED_ARGS=$@
    fi
    # Save the arguments to a file for use by Gradle commands.
    # shellcheck disable=SC2094
    printf '%s\n' "$QUOTED_ARGS" >"$APP_HOME/gradle/args"
}

exec "$JAVACMD" "$@"
